### PR TITLE
Allow MacVim to be used as PR message editor

### PR DESCRIPTION
**Pull request by indirect**

### CODE REVIEW

**Comment by msoyupak** [comment]
@nikhilmat is the right person to take a look at this

**Comment by indirect** [comment]
@robbiegill you're the last person to merge a PR to this repo, can you review this, or point me to the right person? :grimacing:

**Comment by robbiegill** [comment]
@alfred accept!

**Comment by zp-alfred** [comment]
Accepted by robbiegill!

**Pull request merged**
